<?php

return [
     
    [
        'bio' => 'Insegnante di musica con anni di esperienza.',
        'cv' => 'cv1.pdf',
        'photo' => 'Alessandro_Ebreo_violoncellista.png',
        'phone' => 3331234567,
        'service' => 'Lezione Privata',
    ],
    [
        'bio' => 'Appassionata nell\'insegnare musica a tutte le età.',
        'cv' => 'cv2.pdf',
        'photo' => 'Alessio_Vietri_Batterista.png',
        'phone' => 3359876543,
        'service' => 'Lezione Privata',
    ],
    [
        'bio' => 'Insegnante di musica esperto con una passione per la composizione.',
        'cv' => 'cv3.pdf',
        'photo' => 'Andrea_Piani_cantante.png',
        'phone' => 3405555555,
        'service' => 'Lezione Privata',
    ],
    [
        'bio' => 'Insegnante di canto con un amore per la lirica.',
        'cv' => 'cv4.pdf',
        'photo' => 'Emanuele_Verità_Pianista.png',
        'phone' => 3493333333,
        'service' => 'Lezione Privata',
    ],
    [
        'bio' => 'Chitarrista professionista e compositore.',
        'cv' => 'cv5.pdf',
        'photo' => 'Francesco Di Corpo Chitarrista.png',
        'phone' => 3426666666,
        'service' => 'Concerto',
    ],
    [
        'bio' => 'Insegnante di violino con una passione per la musica classica.',
        'cv' => 'cv6.pdf',
        'photo' => 'Francesco_Bonandin_Trombettista.png',
        'phone' => 3469999999,
        'service' => 'Lezione Privata',
    ],
    [
        'bio' => 'Insegnante di musica moderna e pop.',
        'cv' => 'cv7.pdf',
        'photo' => 'Jane_Cantante.png',
        'phone' => 3477777777,
        'service' => 'Lezione Privata',
    ],
    [
        'bio' => 'Pianista professionista con esperienza in musica classica e jazz.',
        'cv' => 'cv8.pdf',
        'photo' => 'Jane_Gne_Arpista.png',
        'phone' => 3488888888,
        'service' => 'Lezione Privata',
    ],
    [
        'bio' => 'Insegnante di musica per bambini e giovani talenti.',
        'cv' => 'cv9.pdf',
        'photo' => 'Jennifer_Formicola_Cantante.png',
        'phone' => 3492222222,
        'service' => 'Lezione Privata',
    ],
    [
        'bio' => 'Insegnante di flauto con passione per la musica classica.',
        'cv' => 'cv10.pdf',
        'photo' => 'Luca_Vita_Violoncellista.png',
        'phone' => 3494444444,
        'service' => 'Lezione Privata',
    ],
    [
        'bio' => 'Insegnante di batteria con esperienza nel rock e nell\'heavy metal.',
        'cv' => 'cv11.pdf',
        'photo' => 'Marco Campisi Batterista.png',
        'phone' => 3471111111,
        'service' => 'Lezione Privata',
    ],
    [
        'bio' => 'Insegnante di teoria musicale e armonia.',
        'cv' => 'cv12.pdf',
        'photo' => 'Marco_Caggiano_Cantante.png',
        'phone' => 3405555555,
        'service' => 'Lezione Privata',
    ],
    [
        'bio' => 'Insegnante di chitarra elettrica con esperienza nella musica rock e blues.',
        'cv' => 'cv13.pdf',
        'photo' => 'Marcos Fuentes Painista.png',
        'phone' => 3426666666,
        'service' => 'Concerto',
    ],
    [
        'bio' => 'Insegnante di percussioni e ritmi tribali.',
        'cv' => 'cv14.pdf',
        'photo' => 'Matteo Bonesini Violoncellista.png',
        'phone' => 3469999999,
        'service' => 'Lezione Privata',
    ],
    [
        'bio' => 'Insegnante di composizione e arrangiamento musicale.',
        'cv' => 'cv15.pdf',
        'photo' => 'Michela Di Stefano Pianista.png',
        'phone' => 3477777777,
        'service' => 'Lezione Privata',
    ],
    [
        'bio' => 'Insegnante di canto moderno e pop.',
        'cv' => 'cv16.pdf',
        'photo' => 'Maria Caruso Violoncellista.png',
        'phone' => 3488888888,
        'service' => 'Lezione Privata',
    ],
    [
        'bio' => 'Insegnante di chitarra acustica e fingerstyle.',
        'cv' => 'cv17.pdf',
        'photo' => 'Marta Baggiano Violoncellista.png',
        'phone' => 3492222222,
        'service' => 'Lezione Privata',
    ],
    [
        'bio' => 'Insegnante di composizione e produzione musicale.',
        'cv' => 'cv18.pdf',
        'photo' => 'Matteo Bonesini Violoncellista.png',
        'phone' => 3494444444,
        'service' => 'Lezione Privata',
    ],
    [
        'bio' => 'Insegnante di strumenti a fiato e ensemble.',
        'cv' => 'cv19.pdf',
        'photo' => 'Mauro Formisano Violoncellista.png',
        'phone' => 3471111111,
        'service' => 'Lezione Privata',
    ],
    [
        'bio' => 'Insegnante di composizione e teoria musicale avanzata.',
        'cv' => 'cv20.pdf',
        'photo' => 'Michela Di Stefano Pianista.png',
        'phone' => 3405555555,
        'service' => 'Lezione Privata',
    ],
    [
        'bio' => 'Insegnante di musicoterapia e terapie sonore.',
        'cv' => 'cv21.pdf',
        'photo' => 'Pasquala Rizzo Violoncellista.png',
        'phone' => 3426666666,
        'service' => 'Lezione Privata',
    ],
    [
        'bio' => 'Insegnante di musica tradizionale e folkloristica.',
        'cv' => 'cv22.pdf',
        'photo' => 'Pietro Marilei chitarrista.png',
        'phone' => 3469999999,
        'service' => 'Lezione Privata',
    ],
    [
        'bio' => 'Insegnante di violoncello e musica classica.',
        'cv' => 'cv23.pdf',
        'photo' => 'Pina Slug pianista.png',
        'phone' => 3477777777,
        'service' => 'Lezione Privata',
    ],
    [
        'bio' => 'Insegnante di musica per bambini e giovani talenti.',
        'cv' => 'cv24.pdf',
        'photo' => 'Samuela Conficconi Violoncellista.png',
        'phone' => 3488888888,
        'service' => 'Lezione Privata',
    ],
    [
        'bio' => 'Insegnante di canto lirico e operistico.',
        'cv' => 'cv25.pdf',
        'photo' => 'Santina Nullable pianista.png',
        'phone' => 3492222222,
        'service' => 'Lezione Privata',
    ],
    [
        'bio' => 'Insegnante di musica elettronica e produzione EDM.',
        'cv' => 'cv26.pdf',
        'photo' => 'Sharon Caruso Pianista.png',
        'phone' => 3494444444,
        'service' => 'Lezione Privata',
    ],
    [
        'bio' => 'Insegnante di arpa e musica classica.',
        'cv' => 'cv27.pdf',
        'photo' => 'Simona Buscemi Cantante.png',
        'phone' => 3471111111,
        'service' => 'Lezione Privata',
    ],
    [
        'bio' => 'Insegnante di percussioni africane e ritmi tribali.',
        'cv' => 'cv28.pdf',
        'photo' => 'Simona Caruso Chitarrista.png',
        'phone' => 3405555555,
        'service' => 'Lezione Privata',
    ],
    [
        'bio' => 'Insegnante di chitarra classica e flamenco.',
        'cv' => 'cv29.pdf',
        'photo' => 'Susanna Tutta Panna Chitarrista.png',
        'phone' => 3426666666,
        'service' => 'Lezione Privata',
    ],
    [
        'bio' => 'Insegnante di canto jazz e improvvisazione vocale.',
        'cv' => 'cv30.pdf',
        'photo' => 'Wanda Simeoli Cantante.png',
        'phone' => 3469999999,
        'service' => 'Lezione Privata',
    ],

];
    
