<?php

return [
    'table' => 'teachers',
    'data' => [
        [
            'bio' => 'Insegnante di musica con anni di esperienza.',
            'cv' => 'cv1.pdf',
            'photo' => 'foto1.jpg',
            'phone' => '3331234567',
            'service' => 'Lezione Privata',
        ],
        [
            'bio' => 'Appassionata nell\'insegnare musica a tutte le età.',
            'cv' => 'cv2.pdf',
            'photo' => 'foto2.jpg',
            'phone' => '3359876543',
            'service' => 'Lezione Privata',
        ],
        [
            'bio' => 'Insegnante di musica esperto con una passione per la composizione.',
            'cv' => 'cv3.pdf',
            'photo' => 'foto3.jpg',
            'phone' => '3405555555',
            'service' => 'Lezione Privata',
        ],
        [
            'bio' => 'Insegnante di canto con un amore per la lirica.',
            'cv' => 'cv4.pdf',
            'photo' => 'foto4.jpg',
            'phone' => '3493333333',
            'service' => 'Lezione Privata',
        ],
        [
            'bio' => 'Chitarrista professionista e compositore.',
            'cv' => 'cv5.pdf',
            'photo' => 'foto5.jpg',
            'phone' => '3426666666',
            'service' => 'Concerto',
        ],
        [
            'bio' => 'Insegnante di violino con una passione per la musica classica.',
            'cv' => 'cv6.pdf',
            'photo' => 'foto6.jpg',
            'phone' => '3469999999',
            'service' => 'Lezione Privata',
        ],
        [
            'bio' => 'Insegnante di musica moderna e pop.',
            'cv' => 'cv7.pdf',
            'photo' => 'foto7.jpg',
            'phone' => '3477777777',
            'service' => 'Lezione Privata',
        ],
        [
            'bio' => 'Pianista professionista con esperienza in musica classica e jazz.',
            'cv' => 'cv8.pdf',
            'photo' => 'foto8.jpg',
            'phone' => '3488888888',
            'service' => 'Lezione Privata',
        ],
        [
            'bio' => 'Insegnante di musica per bambini e giovani talenti.',
            'cv' => 'cv9.pdf',
            'photo' => 'foto9.jpg',
            'phone' => '3492222222',
            'service' => 'Lezione Privata',
        ],
        [
            'bio' => 'Insegnante di flauto con passione per la musica classica.',
            'cv' => 'cv10.pdf',
            'photo' => 'foto10.jpg',
            'phone' => '3494444444',
            'service' => 'Lezione Privata',
        ],
        [
            'bio' => 'Insegnante di batteria con esperienza nel rock e nell\'heavy metal.',
            'cv' => 'cv11.pdf',
            'photo' => 'foto11.jpg',
            'phone' => '3471111111',
            'service' => 'Lezione Privata',
        ],
        [
            'bio' => 'Insegnante di teoria musicale e armonia.',
            'cv' => 'cv12.pdf',
            'photo' => 'foto12.jpg',
            'phone' => '3405555555',
            'service' => 'Lezione Privata',
        ],
        [
            'bio' => 'Insegnante di chitarra elettrica con esperienza nella musica rock e blues.',
            'cv' => 'cv13.pdf',
            'photo' => 'foto13.jpg',
            'phone' => '3426666666',
            'service' => 'Concerto',
        ],
        [
            'bio' => 'Insegnante di percussioni e ritmi tribali.',
            'cv' => 'cv14.pdf',
            'photo' => 'foto14.jpg',
            'phone' => '3469999999',
            'service' => 'Lezione Privata',
        ],
        [
            'bio' => 'Insegnante di composizione e arrangiamento musicale.',
            'cv' => 'cv15.pdf',
            'photo' => 'foto15.jpg',
            'phone' => '3477777777',
            'service' => 'Lezione Privata',
        ],
        [
            'bio' => 'Insegnante di canto moderno e pop.',
            'cv' => 'cv16.pdf',
            'photo' => 'foto16.jpg',
            'phone' => '3488888888',
            'service' => 'Lezione Privata',
        ],
        [
            'bio' => 'Insegnante di chitarra acustica e fingerstyle.',
            'cv' => 'cv17.pdf',
            'photo' => 'foto17.jpg',
            'phone' => '3492222222',
            'service' => 'Lezione Privata',
        ],
        [
            'bio' => 'Insegnante di composizione e produzione musicale.',
            'cv' => 'cv18.pdf',
            'photo' => 'foto18.jpg',
            'phone' => '3494444444',
            'service' => 'Lezione Privata',
        ],
        [
            'bio' => 'Insegnante di strumenti a fiato e ensemble.',
            'cv' => 'cv19.pdf',
            'photo' => 'foto19.jpg',
            'phone' => '3471111111',
            'service' => 'Lezione Privata',
        ],
        [
            'bio' => 'Insegnante di composizione e teoria musicale avanzata.',
            'cv' => 'cv20.pdf',
            'photo' => 'foto20.jpg',
            'phone' => '3405555555',
            'service' => 'Lezione Privata',
        ],
        [
            'bio' => 'Insegnante di musicoterapia e terapie sonore.',
            'cv' => 'cv21.pdf',
            'photo' => 'foto21.jpg',
            'phone' => '3426666666',
            'service' => 'Lezione Privata',
        ],
        [
            'bio' => 'Insegnante di musica tradizionale e folkloristica.',
            'cv' => 'cv22.pdf',
            'photo' => 'foto22.jpg',
            'phone' => '3469999999',
            'service' => 'Lezione Privata',
        ],
        [
            'bio' => 'Insegnante di violoncello e musica classica.',
            'cv' => 'cv23.pdf',
            'photo' => 'foto23.jpg',
            'phone' => '3477777777',
            'service' => 'Lezione Privata',
        ],
        [
            'bio' => 'Insegnante di musica per bambini e giovani talenti.',
            'cv' => 'cv24.pdf',
            'photo' => 'foto24.jpg',
            'phone' => '3488888888',
            'service' => 'Lezione Privata',
        ],
        [
            'bio' => 'Insegnante di canto lirico e operistico.',
            'cv' => 'cv25.pdf',
            'photo' => 'foto25.jpg',
            'phone' => '3492222222',
            'service' => 'Lezione Privata',
        ],
        [
            'bio' => 'Insegnante di musica elettronica e produzione EDM.',
            'cv' => 'cv26.pdf',
            'photo' => 'foto26.jpg',
            'phone' => '3494444444',
            'service' => 'Lezione Privata',
        ],
        [
            'bio' => 'Insegnante di arpa e musica classica.',
            'cv' => 'cv27.pdf',
            'photo' => 'foto27.jpg',
            'phone' => '3471111111',
            'service' => 'Lezione Privata',
        ],
        [
            'bio' => 'Insegnante di percussioni africane e ritmi tribali.',
            'cv' => 'cv28.pdf',
            'photo' => 'foto28.jpg',
            'phone' => '3405555555',
            'service' => 'Lezione Privata',
        ],
        [
            'bio' => 'Insegnante di chitarra classica e flamenco.',
            'cv' => 'cv29.pdf',
            'photo' => 'foto29.jpg',
            'phone' => '3426666666',
            'service' => 'Lezione Privata',
        ],
        [
            'bio' => 'Insegnante di canto jazz e improvvisazione vocale.',
            'cv' => 'cv30.pdf',
            'photo' => 'foto30.jpg',
            'phone' => '3469999999',
            'service' => 'Lezione Privata',
        ],
    ]
];
    
